# Generated by Django 6.0.2 on 2026-02-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
