# Generated by Django 6.0.2 on 2026-02-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
