# Generated by Django 6.0.2 on 2026-02-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
